version: '3.3'

volumes:
  postgres_data:
  staticfiles:
  mediafiles:

services:
  db:
    image: postgres:13.1
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: pyscbist/foodgram:latest
    volumes:
      - staticfiles:/code/static
      - mediafiles:/code/media
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:1.19.6
    volumes:
      - staticfiles:/static
      - mediafiles:/media
      - ./nginx/host.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app
