# Generated by Django 2.2.6 on 2021-02-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210208_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='colour',
            field=models.CharField(default=None, max_length=20, verbose_name='Цвет тега'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('title', 'colour')},
        ),
    ]
