# Generated by Django 2.2.6 on 2021-02-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210209_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(max_length=20, verbose_name='Цвет тега'),
        ),
    ]
