# Generated by Django 2.2.6 on 2021-02-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210209_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(related_name='recipe', to='recipes.Tag', verbose_name='Тег'),
        ),
    ]
