# Generated by Django 2.2.6 on 2021-02-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_favorite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase',
            new_name='Content',
        ),
    ]
