# Generated by Django 2.2.6 on 2021-02-16 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20210215_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe_ingredient', through='recipes.Content', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
