# Generated by Django 2.2.6 on 2021-02-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20210216_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_recipe', to='recipes.Recipe', verbose_name='Рецепт'),
        ),
    ]
